name: my-check
on:
  - push
  - pull_request
jobs:
  build:
    runs on: ubuntu-latest
    steps:
      - name: Checks out your repository
        uses: actions/checkout@v2
      - name: Install poetry
        uses: pip install poetry
      - name: Install project
        uses: make install
      - name: Start test
        uses: make test
      - name: Start lint
        uses: make lint
